# .github/workflows/docs-preview.yaml
name: PR docs preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'

jobs:
  deploy-preview:
    uses: qutech-delft/github-actions/.github/workflows/sphinx-docs-preview.yaml@fix/QI2-1219/fix-failing-action-import
    secrets: inherit
