name: Releases

on:
  pull_request:
    push:
      branches:
        - master
  release:
    types:
      - created

jobs:
  publish:
    name: Publish to TestPyPI
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - name: Create commit identifier
        run: echo "COMMIT_ID=`echo ${{ github.sha }} | head -c 5`" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.3.2"
      - name: Version poetry package for test
        if: endsWith(github.ref, '/merge')
        run: poetry version "`poetry version | awk '{print $2}'`+$COMMIT_ID"
      - name: Version poetry package for release
        if: startsWith(github.ref, 'refs/tags')
        run: poetry version "${{  github.ref_name }}+$COMMIT_ID"
      - name: Build poetry package
        run: poetry build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
