name: Releases

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  publish:
    name: Publish to TestPyPI
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      # Setting the proper version
      - name: Get previous Tag
        if: github.ref == 'refs/heads/master'
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.1.0
      - name: Set Build version
        if: github.ref == 'refs/heads/master'
        run: |
          COMMIT_ID=`echo ${{ github.sha }} | head -c 8`
          poetry version "${{ steps.previous_tag.outputs.tag }}+$COMMIT_ID"
      - name: Set Release version
        if: github.event_name == 'release' && github.event.action == 'created'
        run: poetry version ${{ github.ref_name }}

      # Build package
      - name: Build poetry package
        run: poetry build

      # Publishing the package
      - name: Publish distribution 📦 to Test PyPI
        if: github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: pypa/gh-action-pypi-publish@release/v1
