name: Releases

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  publish:
    uses: qutech-delft/github-actions/.github/workflows/poetry-release.yaml@fix/QI2-1219/fix-failing-action-import

